package com.xworkz.exception;

//java 7 ARM feature
//So java 7 one of the improvements was try-with-resources where we can create a resource in
//the try statement itself and use it inside the try-catch block. 
//When the execution comes out of the try-catch block, the runtime environment 
//automatically closes these resources. Sample of try-catch block with this improvement is:
public class JavaARM {
	public static void main(String[] args) {
//		try (MyResource mr = new MyResource()) {
//            System.out.println("MyResource created in try-with-resources");
//        } catch (Exception e) {
//            e.printStackTrace();
//        }

	}
}
